module.exports = {
  STATUS: {
    OPEN: 'INVOICE.OPEN',
    PAID: 'INVOICE.PAID',
    PARTIALLY_PAID: 'INVOICE.PARTIALLY_PAID'
  },
  EVENTS: {
    INVOICE_CREATED: 'INVOICE.CREATED',
    PAYMENT_RECEIVED: 'INVOICE.PAYMENT_RECEIVED'
  }
}